### ISSUE TITLE
Lace Wallet Stuck on loading

### ISSUE THREAD

**Issue by QuaNilo** [input-output-hk/lace#1449]
My lace wallet is stuck on the loading screen, if i inspect the page and check console.logs() i see :
Invalid argument 'walletId': Wallet <walletID here> not found.

I have this error across multiple devices, so i'm guessing uninstalling lace and installing wont fix the issue.

**Comment by case-hub** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@QuaNilo

**Comment by mchappell** [comment]
fixed in https://github.com/input-output-hk/lace/pull/1484

**Comment by HHobeck** [comment]
This problem still occurs in the version 1.17.3 of lace on my computer. My chrome is up to date with version 131.0.6778.86 (Official Build) (64-bit) on windows

![image](https://github.com/user-attachments/assets/c105e083-c673-4700-a56a-0de5efce1c6c)
